name: Docker Image CI
on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag samirls/todofamily-fe

      - name: Docker Push
        run: docker push samirls/todofamily-fe

  SSH:
    needs: build
    name: Deploy and Notification
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY_ED25519 }}
          port: ${{ secrets.PORT }}
          script: |
            cd todo-java/
            sh script.sh

      - name: Discord Notification
        uses: sarisia/actions-status-discord@v1.9.0
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "Frontend Todo Family 2.0"
          description: "Código atualizado no servidor"
          username: GitHub Actions
